services:
  db:
    hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    ports:
      - '8080:8080'
      - '9080:9080'

  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    ports:
      - '8000:8000'

  schema-app:
    build:
      context: ./
    restart: 'no'
    environment:
      DGRAPH_SERVER: http://dgraph_standalone:8080
      SAMPLE_DATA: plain_pubs