
{ 
    queryInfoObject(filter: {
       sdgs: { in: [ sdg_3, sdg_14 ]}
       and: {
        title: { allofterms: "Alkoholkonsum"},
        or: {title: {allofterms: "Waldtherapie als innovative Ansätze"}}
       }
    }) @cascade(fields: [ "persons", "category"]) {

    persons( filter: { department: {in: [department_N, department_P, department_G] } }) {
        initials
        department
    }
    category(filter: { name: { in: [ "Publication" ] } } ) {
        name
    }
    authors: persons {
        fullname
    }
    title
    year 
    sdgs
    link
        } 
}

